export const environment = {
  production: true,
  pre_production: true,
  //API_ENDPOINT: "https://www.asambleas.cl/apps_gaj/api/",
  API_ENDPOINT: '/apps/api/',
  URL_SLIDE: 'https://bingoshowpremium.cl/apps/slides/',
  URL_PDF: 'https://bingoshowpremium.cl/apps/cartones/cartones/',
  URL_PDF_HOME: 'https://bingoshowpremium.cl/apps/pdfs/',
  SITE_KEY_RECAPTCHA: '6LdrqMMZAAAAACMaS3duA9rxbULrRcGmQlQ9q2mW',
  DIRECCION: 'Merced 480 Piso 2, Santiago - Chile',
  TELEFONO:'(+56 2) 2588 8800',
  CONTACTO:'contacto@rayensalud.com',
  WEB:'https://www.rayensalud.com/',
  FACEBOOK:'https://www.facebook.com/bingonario.net/',
  INSTAGRAM:'https://www.instagram.com/bingonario/',
  YOUTUBE: 'https://www.youtube.com/channel/UCpMAXhophHJjuka1NTww4Dw',
  URL_FLOW: 'https://sandbox.flow.cl/api',
  API_KEY_FLOW: '4E6FFF0A-B357-4509-BA5E-43AAL1B3E32D',
  SECRET_KEY_FLOW: 'c221b50487244ab851b38f2fc78fe362273b592c',
  URL_CONFRIMATION: 'https://bingoshowpremium.cl/apps/correctobingonario',
  URL_RETURN: 'https://bingoshowpremium.cl/apps/retornobingonario',
  URL_ERROR: 'https://bingoshowpremium.cl/apps/errorbingonario',
  HOME_ESTATICO: false,
  USA_PAYU: false,
  MERCHANT_ID_PAYU: 508029,
  ACCOUNT_ID_PAYU: 512321, //COLOMBIA
  API_KEY_PAYU: '4Vj8eK4rloUd272L48hsrarnUA',
  API_LOGIN_PAYU: 'pRRXKOl8ikMmt9u',
  URL_REPORTS_PAYU: 'https://sandbox.api.payulatam.com/reports-api/4.0/service.cgi',
  URL_PAYMENT_PAYU: 'https://sandbox.api.payulatam.com/payments-api/4.0/service.cgi',
  URL_WEBCHECK_PAYU: 'https://sandbox.checkout.payulatam.com/ppp-web-gateway-payu/',
  API_KEY_CONVERTER: '252ae632a706147d020b',
  URL_CONVERTER: 'https://free.currconv.com/api/v7/convert'
};
